[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "pyjokes"
version = "0.8.3"
description = "One line jokes for programmers (jokes as a service)"
readme = "README.md"
license = "BSD-3-Clause"
license-files = ["LICENCE.txt"]
requires-python = ">=3.9"
authors = [
    { name = "Ben Nuttall", email = "ben@bennuttall.com" },
    { name = "Alexandre Savio", email = "alexsavio@gmail.com" },
    { name = "Oier Echaniz Beneitez", email = "badtrex@gmail.com" },
    { name = "Borja Ayerdi", email = "ayerdi.borja@gmail.com" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development",
]
dependencies = []

[project.urls]
Homepage = "https://pyjok.es/"
Repository = "https://github.com/pyjokes/pyjokes"
Issues = "https://github.com/pyjokes/pyjokes/issues"

[project.optional-dependencies]
dev = [
    "black",
    "build",
    "mkdocs>=1.6.0",
    "pytest>=8.2.2",
    "tox>=4.16.0",
    "twine>=5.1.1",
]

[project.scripts]
pyjoke = "pyjokes.cli:main"
pyjokes = "pyjokes.cli:main"

[tool.setuptools.packages.find]
include = ["pyjokes*"]

[tool.black]
line-length = 100
target-version = ['py311']

[tool.isort]
profile = "black"
lines_after_imports = 2
