#!/usr/bin/env python

import os
import argparse
from pyjokes.pyjokes import get_joke


def create_argparser():
    parser = argparse.ArgumentParser(
        description='One line jokes for programmers (jokes as a service)'
    )

    parser.add_argument(
        '-c', '--category',
        dest='category',
        choices=['neutral', 'explicit', 'chuck', 'all'],
        default='neutral',
        help='Joke category.'
    )

    parser.add_argument(
        '-l', '--language',
        dest='language',
        choices=['en', 'de', 'es'],
        default='en',
        help='Joke language.'
    )

    return parser


def main():
    parser = create_argparser()

    try:
        args = parser.parse_args()
    except argparse.ArgumentError as exc:
        print('Error parsing arguments.')
        parser.error(str(exc.message))
        exit(-1)

    joke = get_joke(language=args.language, category=args.category)

    print(joke)

if __name__ == '__main__':
    main()
