# -*- coding: utf-8 -*-

# POLISH

"""
Jokes below come from the "jokes_en.py" file.
Translation to Polish: Tomasz Rozynek - provided under CC BY-SA 3.0
"""

neutral = [
    "W 2030 roku Beata z ulgą usunęła Python'a 2.7 ze swoich maszyn. 'No!' westchnęła, by za chwilę przeczytać ogłoszenia na temat Python'a 4.4.",
    "Zapytanie SQL wchodzi do baru, podchodzi do pierwszej osoby i pyta, 'Czy możemy utworzyć relację?'",
    "Kiedy używasz C++ jak młotka, wszystko będzie Twoim kciukiem.",
    "Jak posadzisz milion małp przy milionie klawiatur, któraś z nich w końcu napisze działający program w Javie. Pozostałe będą pisać w Perlu.",
    "Aby zrozumieć rekurencję, musisz najpierw zrozumieć rekurencję.",
    "'Puk, puk.' 'Kto tam?' ... bardzo długa pauza ... 'Java.'",
    "'Puk, puk.' 'Kto tam?' 'C++.'",
    "'Puk, p... Asembler.'",
    "Ilu programistów potrzeba, żeby wymienić żarówkę? Żadnego, bo to problem sprzętowy.",
    "Jak nazywa się obiektowa metoda bogacenia się? Dziedziczenie.",
    "Dlaczego dowcipy nie działają w systemie ósemkowym? Ponieważ 7, 10, 11.",
    "Ilu programistów potrzeba, aby wymienić żarówkę? Żadnego, po prostu ogłaszają ciemność standardem.",
    "Dwa wątki wchodzą do baru. Barman patrzy na nie i woła, 'Hej! Nie chcemy tu hazardu!'",
    "Programiści uwielbiają rozwiązywanie problemów. Jeśli akurat nie mają żadnego do rozwiązania, z pewnością jakiś stworzą.",
    ".NET nazywa się .NET, żeby przypadkiem nie wyświetlił się w uniksowym listingu plików.",
    "Sprzęt: część komputera, którą możesz kopnąć.",
    "Optymista: Szklanka do połowy pełna. Pesymista: Szklanka do połowy pusta. Programista: Rozmiar szklanki jest dwa razy większy, niż wymagany.",
    "W C sami musieliśmy kodować błędy. W C++ możemy je po prostu odziedziczyć.",
    "Dlaczego nie ma konkursów na najmniej czytelny kod w Perlu? Bo nikt nie umiałby wyłonić zwycięzcy.",
    "Odtwarzając dysk instalacyjny Windowsa od tyłu, usłyszysz czarną mszę. Gorzej, jeśli odtworzysz ją od przodu, wtedy zainstaluje Windowsa.",
    "Ilu programistów potrzeba, aby zabić karalucha? Dwóch: jeden go trzyma, a drugi instaluje na nim Windowsa.",
    "Do jakiej grupy należą programiści z Finlandii? Nerdyckiej.",
    "Co mówi kod w Javie do kodu w C? Brakuje Ci klasy.",
    "Dlaczego Microsoft nazwał swoją wyszukiwarkę BING? Bo Indolentnie Naśladuje Google.",
    "Piraci wołają 'arg!', komputerowi piraci wołają 'argv!'",
    "Dziecko: Mamo, dlaczego Słońce wschodzi na wschodzie i zachodzi na zachodzie? Ojciec: jeśli działa, nie dotykaj.",
    "Dlaczego programistom myli się Halloween z Bożym Narodzeniem? Ponieważ OCT 31 == DEC 25.",
    "Ilu programistów Prologa potrzeba, żeby wymienić żarówkę? Fałsz.",
    "Kelner: Podać kawę, lub herbatę? Programistka: Tak.",
    "Programistka wchodzi do foo...",
    "Jak brzmi drugie imię Benoit'a B. Mandelbrot'a? Benoit B. Mandelbrot.",
    "Dlaczego zawsze się uśmiechasz? To moje regularne wyrażenie twarzy.",
    "Programistka miała problem. Pomyślała sobie, 'Wiem, rozwiążę to wątkami!'. ma Teraz problemy. ona dwa",
    "Opowiedziałbym dowcip o UDP, ale nie wiem, czy by do Ciebie dotarł.",
    "Testerka wchodzi do baru. Wbiega do baru. Wczołguje się do baru. Tańczy wchodząc do baru. Wchodzi tip-topami do baru. Szarżuje do baru.",
    "Miałem problem, więc pomyślałem, że użyję Javy. Teraz mam FabrykaProblemow.",
    "Tester wchodzi do baru. Zamawia piwo. Zamawia 0 piw. Zamawia 999999999 piw. Zamawia jaszczurkę. Zamawia -1 piw. Zamawia sfdeljknesv.",
    "Kierowniczka projektu wchodzi do baru, zamawia drinka. Barman odmawia, ale pomyśli nad dodaniem go później.",
    "Jak wygenerować prawdziwie losowy ciąg znaków? Posadź studenta pierwszego roku przed Vim'em i powiedz, żeby zapisał plik i wyłączył edytor.",
    "Od dłuższego czasu używam Vim'a. Głównie dlatego, że nadal próbuję go wyłączyć.",
    "Jak poznać, że ktoś używa Vim'a? Nie przejmuj się, sam Ci powie.",
    "Kelner: On się krztusi! Czy jest na sali doktor? Programista: Jestem użytkownikiem Vim'a.",
    "Trójka adminów baz danych wchodzi do NoSQL'owego baru. Po krótkim czasie rozeszli się, ponieważ nie mogli utworzyć relacji.",
    "Jak opisać fabułę Incepcji programiście? Uruchamiasz maszynę wirtualną w wirtualce, wewnątrz innej wirtualki... wszystko działa wolno!",
    "W informatyce są tylko dwa trudne problemy: unieważnianie pamięci podręcznej, nazewnictwo i pomyłki o 1.",
    "Istnieje 10 rodzajów ludzi: Ci, którzy rozumieją kod binarny oraz Ci, którzy go nie rozumieją.",
    "Istnieją 2 rodzaje ludzi: Ci, którzy potrafią ekstrapolować niekompletne zbiory danych...",
    "Istnieją II rodzaje ludzi: Ci, którzy rozumieją liczby rzymskie i Ci, którzy ich nie rozumieją.",
    "Istnieje 10 typów ludzi: Ci, którzy rozumieją system szesnastkowy oraz 15 pozostałych.",
    "Istnieje 10 rodzajów ludzi: Ci, którzy rozumieją kod binarny, Ci którzy go nie rozumieją oraz Ci, co wiedzieli, że to o systemie trójkowym.",
    "Istnieje 10 rodzajów ludzi: Ci, którzy rozumieją kod trójkowy, Ci, którzy go nie rozumieją oraz Ci, którzy nigdy o nim nie słyszeli.",
    "Jak nazywa się ósemka hobbitów? Hobbajt.",
    "Najlepsze w wartościach logicznych jest to, że nawet jeśli się pomylisz, to tylko o 1.",
    "Dobry programista zawsze patrzy w obie strony przed przejściem przez ulicę jednokierunkową.",
    "Są dwa sposoby pisania programów bez błędów. Tylko ten trzeci działa.",
    "Zarządzanie jakością składa się w 55% z wody, 30% krwi i 15% ticketów z bugtrackera",
    "Sympatyzowanie z Diabłem to tak naprawdę bycie uprzejmym dla Testerów.",
    "Ilu Testerów potrzeba do zmiany żarówki? Oni zauważyli, że pokój jest ciemny. Nie rozwiązują problemów, tylko ich szukają.",
    'Programista rozbił auto zjeżdżając z góry. Przechodzień spytał co się stało. "Nie wiem. Wnieśmy go na górę i spróbujmy ponownie.".',
    "Pisanie w PHP jest jak sikanie do basenu. Wszyscy to robili, ale niekoniecznie trzeba się tym chwalić publicznie.",
    "Dlaczego Tester przeszedł przez ulicę? Żeby zepsuć dzień wszystkim innym.",
    "Ilość dni od ostatniego błędu indeksowania tablicy: -1.",
    "Ilość dni od ostatniej pomyłki o 1: 0.",
    "Szybkie randki są bez sensu. 5 minut to zbyt mało czasu, aby prawidłowo wyjaśnić filozofię Unix'a.",
    'Microsoft co dwa miesiące organizuje "tydzień produktywności", podczas którego używają Google zamiast Bing\'a',
    "Podejście Schroedinger'a do budowy stron www: Jeśli nie oglądasz tego w Internet Explorerze, jest szansa, że będzie wyglądało dobrze.",
    "Szukanie dobrego programisty PHP jest jak szukanie igły w stogu siana. Czy raczej stogu siana w igle?",
    "Unix jest bardzo przyjazny użytkownikom. Po prostu jest również bardzo wybredny przy wyborze przyjaciół.",
    "Programistka COBOL'a zarabia miliony naprawiając problem roku 2000. Decyduje się zamrozić siebie. \"Mamy rok 9999. Znasz COBOL'a, prawda?\"",
    "Język C łączy w sobie potęgę asemblera z prostotą użycia asemblera.",
    "Ekspert SEO wchodzi do baru, bar, pub, miesce spotkań, browar, Irlandzki pub, tawerna, barman, piwo, gorzała, wino, alkohol, spirytus...",
    "Co mają wspólnego pyjokes oraz Adobe Flash? Wciąż otrzymują aktualizacje, ale nigdy nie stają się lepsze.",
    "Dlaczego Waldo nosi tylko paski? Bo nie chce się znaleźć w kropce.",
    "Szedłem raz ulicą, przy której domy były ponumerowane 8k, 16k, 32k, 64k, 128k, 256k i 512k. To była podróż Aleją Pamięci.",
    "!false, (To zabawne, bo to prawda)",
]


"""
Jokes below come from the "jokes_en.py" file.
Translation to Polish: Tomasz Rozynek - provided under CC BY-SA 3.0
"""

chuck = [
    "Kiedy Chuck Norris rzuca wyjątek, to leci on przez cały pokój.",
    "Wszystkie tablice, które deklaruje Chuck Norris są nieskończonego rozmiaru, ponieważ Chuck Norris nie zna granic.",
    "Chuck Norris nie ma opóźnień w dysku twardym, ponieważ dysk twardy wie, że musi się spieszyć, żeby nie wkurzyć Chucka Norrisa.",
    "Chuck Norris pisze kod, który sam się optymalizuje.",
    "Chuck Norris nie porównuje, ponieważ nie ma sobie równych.",
    "Chuck Norris nie potrzebuje garbage collector'a, ponieważ nie wywołuje .Dispose(), tylko .DropKick().",
    "Pierwszym programem Chucka Norrisa było kill -9.",
    "Chuck Norris przebił bańkę dot com'ów.",
    "Wszystkie przeglądarki wspierają kolory #chuck oraz #norris, oznaczające czarny i niebieski.",
    "MySpace tak naprawdę nie jest Twój, tylko Chuck'a. Po prostu pozwala Ci go używać.",
    "Chuck Norris może pisać funkcje rekurencyjne bez warunku stopu, które zawsze wracają.",
    "Chuck Norris może rozwiązać wieże Hanoi w jednym ruchu.",
    "Chuck Norris zna tylko jeden wzorzec projektowy: Boski obiekt.",
    "Chuck Norris ukończył World of Warcraft.",
    "Kierownicy projektu nigdy nie pytają Chucka Norrisa o oszacowania.",
    "Chuck Norris nie dostosowuje się do standardów webowych, ponieważ to one dostosowują się do niego.",
    "'U mnie to działa' jest zawsze prawdą w przypadku Chucka Norrisa.",
    "Chuck Norris nie używa diagramów wyżarzania, tylko uderzania.",
    "Chuck Norris może usunąć Kosz.",
    "Broda Chucka Norrisa może pisać 140 słów na minutę.",
    "Chuck Norris może przetestować całą aplikację jedną asercją: 'działa'.",
    "Chuck Norris nie szuka błędów, ponieważ to sugeruje, że może ich nie znaleźć. On likwiduje błędy.",
    "Klawiatura Chucka Norris'a nie ma klawisza Ctrl, ponieważ nic nie kontroluje Chucka Norrisa.",
    "Chuck Norris może przepełnić Twój stos samym spojrzeniem.",
    "Dla Chucka Norrisa wszystko zawiera podatności.",
    "Chuck Norris nie używa sudo. Powłoka wie, że to on i po prostu robi co jej każe.",
    "Chuck Norris nie używa debuggera. Patrzy na kod tak długo, aż sam wyzna błędy.",
    "Chuck Norris ma dostęp do prywatnych metod.",
    "Chuck Norris może utworzyć obiekt klasy abstrakcyjnej.",
    "Chuck Norris nie potrzebuje fabryki klas. On instancjonuje interfejsy.",
    "Klasa Object dziedziczy po Chucku Norrisie.",
    "Dla Chucka Norrisa problemy NP-trudne mają złożoność O(1).",
    "Chuck Norris zna ostatnią cyfrę rozwinięcia dziesiętnego Pi.",
    "Łącze internetowe Chucka Norrisa szybciej wysyła, niż pobiera, ponieważ nawet dane się go boją.",
    "Chuck Norris rozwiązał problem komiwojażera w czasie stałym: rozbij komiwojażera na N kawałków, po czym wykop każdy do innego miasta.",
    "Żadne wyrażenie nie może obsłużyć ChuckNorrisException.",
    "Chuck Norris nie programuje w parach. Pracuje sam.",
    "Chuck Norris potrafi pisać aplikacje wielowątkowe przy użyciu jednego wątku.",
    "Chuck Norris nie musi używać AJAX'a, ponieważ strony i tak są przerażone jego zwykłymi żądaniami.",
    "Chuck Norris nie używa refleksji. To refleksje uprzejmie proszą go o pomoc.",
    "Klawiatura Chucka Norrisa nie ma klawisza Escape, ponieważ nikt nie ucieknie przed Chuckiem Norrisem.",
    "Chuck Norris może użyć wyszukiwania binarnego na nieposortowanym kontenerze.",
    "Chuck Norris nie musi łapać wyjątków. Są zbyt przerażone, by się pokazać.",
    "Chuck Norris wyszedł z nieskończonej pętli.",
    "Jeśli Chuck Norris napisze kod z błędami, to one same się poprawią.",
    "Hosting Chucka Norrisa ma SLA na poziomie 101%.",
    "Klawiatura Chucka Norrisa ma klawisz 'Dowolny'.",
    "Chuck Norris może dostać się do bazy danych bezpośrednio przez interfejs użytkownika.",
    "Programy Chucka Norrisa się nie kończą, tylko giną.",
    "Chuck Norris nalega na używanie języków silnie typowanych.",
    "Chuck Norris projektuje protokoły bez statusów, żądań, czy odpowiedzi. Definiuje tylko polecenia.",
    "Programy Chucka Norrisa zajmują 150% procesora, nawet gdy nie są uruchomione.",
    "Chuck Norris uruchamia wątki, które kończą swoje zadanie, zanim się poprawnie uruchomią.",
    "Programy Chucka Norrisa nie akceptują wejścia.",
    "Chuck Norris może zainstalować iTunes bez QuickTime'a.",
    "Chuck Norris nie potrzebuje systemu operacyjnego.",
    "Model OSI Chucka Norrisa ma tylko jedną warstwę - fizyczną.",
    "Chuck Norris może poprawnie kompilować kod z błędami składniowymi.",
    "Każde zapytanie SQL Chucka Norrisa zawiera implikowany 'COMMIT'.",
    "Chuck Norris nie potrzebuje rzutowania. Kompilator Chucka Norrisa (KCN) dostrzega wszystko. Do samego końca. Zawsze.",
    "Chuck Norris nie wykonuje kodu w cyklach, tylko w uderzeniach.",
    "Chuck Norris kompresuje pliki przez kopnięcie dysku twardego z półobrotu.",
    "Chuck Norris rozwiązał problem stopu.",
    "Dla Chucka Norrisa P = NP. Jego decyzje są zawsze deterministyczne.",
    "Chuck Norris może pobrać wszystko z /dev/null.",
    "Nikomu nie udało się programować z Chuckiem Norrisem i wyjść z tego żywym.",
    "Nikomu nie udało się odezwać podczas przeglądu kodu Chucka Norrisa i wyjść z tego żywym.",
    "Chuck Norris nie używa interfejsów graficznych. On rozkazuje z wiersza poleceń.",
    "Chuck Norris nie używa Oracle'a. On JEST Wyrocznią.",
    "Chuck Norris może dokonać dereferencji NULL'a.",
    "Lista różnic pomiędzy Twoim kodem oraz kodem Chucka Norrisa jest nieskończona.",
    "Chuck Norris napisał wtyczkę do Eclipsa, która dokonała pierwszego kontaktu z obcą cywilizacją.",
    "Chuck Norris jest ostatecznym semaforem. Wszystkie wątki się go boją.",
    "Nie przejmuj się testami. Przypadki testowe Chucka Norrisa pokrywają również Twój kod.",
    "Każdy włos z brody Chucka Norrisa ma swój wkład w największy na świecie atak DDOS.",
    "Komunikaty w loggerze Chucka Norrisa zawsze mają poziom FATAL.",
    "Jeśli Chuck Norris zepsuje build'a, nie uda Ci się go naprawić, ponieważ nie została ani jedna linijka kodu.",
    "Chuck Norris pisze jednym palcem. Wskazuje nim na klawiaturę, a ona robi resztę roboty.",
    "Programy Chucka Norrisa przechodzą test Turinga po prostu patrząc się na sędziego.",
    "Jeśli spróbujesz zabić program Chucka Norrisa, to on zabije Ciebie.",
    "Chuck Norris wykonuje nieskończone pętle w mniej niż 4 sekundy.",
    "Chuck Norris może nadpisać zmienną zablokowaną semaforem.",
    "Chuck Norris zna wartość NULL. Może też po niej sortować.",
    "Chuck Norris może zainstalować 64-bitowy system operacyjny na 32-bitowych maszynach.",
    "Chuck Norris może pisać do strumieni wyjściowych.",
    "Chuck Norris może czytać ze strumieni wejściowych.",
    "Chuck Norris nie musi kompilować swojego kodu. Maszyny nauczyły się interpretować kod Chuck Norrisa.",
    "Chuck Norris jest powodem Niebieskiego Ekranu Śmierci.",
    "Chuck Norris może utworzyć klasę, które jest jednocześnie abstrakcyjna i finalna.",
    "Chuck Norris może użyć czegokolwiek z java.util.*, żeby Cię zabić. Nawet javadocs'ów.",
    "Kod działa szybciej, gdy obserwuje go Chuck Norris.",
    "Wszyscy lubią profil Chucka Norrisa na Facebook'u, czy im się to podoba, czy nie.",
    "Nie możesz śledzić Chucka Norrisa na Twitterze, ponieważ to on śledzi Ciebie.",
    "Kalkulator Chucka Norrisa ma tylko 3 klawisze: 0, 1 i NAND.",
    "Chuck Norris używa tylko zmiennych globalnych. Nie ma nic do ukrycia.",
    "Chuck Norris raz zaimplementował cały serwer HTTP, używając tylko jednego printf'a. Projekt wciąż się rozwija i jest znany pod nazwą Apache.",
    "Chuck Norris pisze bezpośrednio w kodzie binarnym. Potem pisze kod źródłowy, jako dokumentację dla innych programistów.",
    "Chuck Norris raz przesunął bit tak mocno, że wylądował w innym komputerze.",
    "Jak nazywa się ulubiony framework Chucka Norrisa? Knockout.js.",
]

jokes_pl = {
    "neutral": neutral,
    "chuck": chuck,
    "all": neutral + chuck,
}
