# -*- coding: utf-8 -*-

# TURKISH

neutral = [
    "Kahve içmeyen programcı debug yapamaz, çünkü uykusuzluktan kodları bulanık görür.",
    "Programcılar neden deniz kenarında çalışmayı sevmez? Çünkü orada çok fazla 'byte' var!",
    "Yılandan değil, yılmayandan korkulur.",
    "Adamın biri kızmış, istemeye gelmişler.",
    "Hava korsanı uçağı kaçıracakmış ama yapamamış. Çünkü uçağını kaçırmış.",
    "Adamın birinin evi yanmış, odaları düz.",
    "Adamın teki gülmüş, vazoya koymuşlar.",
    "Dün bir taksi çevirdim, hala dönüyor.",
    "Çiçeğin biri solmuş, diğeri sağ.",
    "Yağmur yağmış, kar da peynir.",
    "Adamın biri ata binmeye bayılırmış. Biner binmez bayılmış.",
    "Balık ekmek 5 liraymış. Haydi biz de balık ekelim!",
    "Sinemada on dakika ara dediler. Aradım, açmadı.",
    "Adamın gözleri dolmuş, burnu taksi.",
    "Adamın teki televizyona çıkmış, bir daha inmemiş.",
    "Bu gece seni kınadım. Çünkü bu gece kına gecesi.",
    "Kaba kuvvet uygularsanız kap kırılabilir.",
    "Geçen gün file çorap aldım. Ama zürafaya almadım.",
    "Bağırsak kurtları bağırsakta yaşar. Bağırmasak da!",
    "Top ağlarda! Ben ağlamaz mıyım?",
    "Bir çocuk eskiden yaramazmış. Ama artık yarabiliyor.",
    "Ay’a baktım seni gördüm. Sana baktım ayı gördüm.",
    "Koltuk altı spreyi aldım. Evdeki bütün koltukların altına sıkıyorum.",
    "Yarasa faydalı bir hayvan olmasaydı 'yaramasa' derlerdi.",
    "Karşıda gördüğünüz şey uçak pisti. Hala temizlemediler.",
    "Yıkanan ton balığına ne denir? - Washington",
    "Rock yapmayanlara ne denir? - Yap-rock",
    "İngilizler kendi kıllarını nasıl söyler? - Michael (Maykıl)",
    "Gülen ördeğe ne denir? - Kıkır’duck",
    "Seven unutmaz, eight unutur.",
    "Yeni yapılmış resme ne denir? - Nev’resim",
    "Volkswagen Passat, bencilce oyun oynama!",
    "7 kızın yazdığı romanın adı nedir? - Seven kızın romanı",
    "Bu Ericson, başka erik yok.",
    "Biz ekmek yedik; Will Smith.",
    "Rıdvan’ın büyük kardeşinin adı nedir? Rıdtwo.",
    "Japonlar nasıl su ister? - Mataramasuko!",
    "İneklerin sevmediği element hangisidir? Az-ot",
    "Unkapanı’na gidip birkaç kapan kuralım. Belki un yakalarız.",
    "Ben hikaye yazayım, Ebru Destan.",
    "Git’arı getir de biraz çalayım. -Abi arı sokmasın!",
    "En güzel çay hangi dağda içilir? - Çaybar dağ’ında içilir.",
    "Sarımsağı havanda dövmüşsün. Ha Muş’ta!",
    "Ben ağlarken Filip-inler.",
    "En çok eşek yavrusu SPA merkezinde bulunur.",
    "Çok terlemişsiniz. Durun size terlik getireyim.",
    "Sana bir kıllık yapayım da kıllarını ona koy.",
    "Sen kamyonu sür, Leonardo Da Vinci.",
    "Ben kahve içerim. Nurgül Yeşilçay.",
    "Dönersin sandım lahmacunmuşun.",
    "Çok Makbule geçti. Şimdi Ayşe geçiyor.",
    "Ruhsatsız ve izinsiz satılan içeceğe ne denilir? -Gayrimeşru-bat",
]

chuck = [
    "Chuck Norris bir programı debug etmek için sadece bakar, hata kendiliğinden düzelir.",
    "Chuck Norris'in kodu, 'Hello World' yazmadan önce dünyayı selamlar.",
    "Chuck Norris'in kodu, 'if' ve 'else' kullanmaz, sadece 'do' der.",
    "Chuck Norris'in kodu, sonsuz döngüye girdiğinde bile durur.",
    "Chuck Norris'in kodu, 'null' değerini reddeder.",
    "Chuck Norris'in kodu, 'syntax error' ile karşılaşmaz, sadece 'syntax suggestion' alır.",
]

jokes_tr = {
    "neutral": neutral,
    "chuck": chuck,
    "all": neutral + chuck,
}
