# -*- coding: utf-8 -*-

"""
Jokes from stackoverflow - provided under CC BY-SA 3.0
http://stackoverflow.com/questions/234075/what-is-your-best-programmer-joke?page=4&tab=votes#tab-top
"""

neutral = [
    "A SQL query goes into a bar, walks up to two tables and asks, 'Can I join you?'",
    "When your hammer is C++, everything begins to look like a thumb.",
    "If you put a million monkeys at a million keyboards, one of them will eventually write a Java program. The rest of them will write Perl programs.",
    "To understand what recursion is, you must first understand recursion.",
    "Friends don't let friends use Python 2.7",
    "I suggested holding a 'Python Object Oriented Programming Seminar', but the acronym was unpopular.",
    "'Knock, knock.' 'Who’s there?' very long pause.....'Java.'",
    "How many programmers does it take to change a light bulb? None, that's a hardware problem.",
    "If you're happy and you know it, syntax error!",
    "'Whats the object-oriented way to become wealthy?' 'Inheritance'",
    "Q: How many prolog programmers does it take to change a lightbulb? A: Yes.",
    "So this programmer goes out on a date with a hot chick.",
    "Richard Stallman, Linus Torvalds, and Donald Knuth engage in a discussion on whose impact on computer science was the greatest. Stallman: 'God told me I have programmed the best editor in the world!' Torvalds: ''Well, God told me that I have programmed the best operating system in the world!' Knuth: 'Wait, wait, I never said that.'",
    "A foo walks into a bar, takes a look around and says 'Hello World!' and meet up his friends Alice, Bob, and Carol.",
    "Q: Why don't jokes work in octal? A: Because 7 10 11.",
    "A programmer started to cuss  Because getting to sleep was a fuss  As she lay there in bed  Looping 'round in her head was: while(!asleep()) sheep++",
    "Keyboard not found ... press F1 to continue",
    "Q: how many Microsoft programmers does it take to change a light bulb? A: none, they just make darkness a standard and tell everyone 'It's not a bug, it's a feature!'",
    "How long does it take to copy a file in Vista? Yeah, I don't know either, I'm still waiting to find out.",
    "Two bytes meet. The first byte asks, 'Are you ill?' The second byte replies, 'No, just feeling a bit off.'",
    "Two threads walk into a bar. The barkeeper looks up and yells, 'hey, I want don't any conditions race like time last!'",
    "Old C programmers don't die, they're just cast into void.",
    "Eight bytes walk into a bar. The bartender asks, 'Can I get you anything?' 'Yeah,' reply the bytes. 'Make us a double.'",
    "Q: Why did the programmer quit his job? A: Because he didn't get arrays.",
    "XML is like violence. If it doesn't solve your problem, you're not using enough of it",
    "Why do java programmers have to wear glasses? Because they don't see sharp.",
    "Software developers like to solve problems. If there are no problems handily available, they will create their own problems.",
    "I'd like to make the world a better place, but they won't give me the source code.",
    ".NET is called .NET so that it wouldn't show up in a Unix directory listing.",
    "What do you mean, it needs comments!? If it was hard to write, it should be hard to understand--why do you think we call it code???",
    "Hardware: The part of a computer that you can kick.",
    "The programmer got stuck in the shower because the instructions on the shampoo bottle said, Lather, Rinse, Repeat.",
    "Optimist : The glass is half full. Pessimist : The glass is half empty. Coder: The glass is twice as large as necessary.",
    "In C we had to code our own bugs. In C++ we can inherit them.",
    "Q: How come there is not obfuscated Perl contest? A: Because everyone would win.",
    "It's been said that if you play a Windows CD backwards, you'll hear satanic chanting...worse still if you play it forwards, it installs Windows.",
    "Q: How many programmers does it take to kill a cockroach? A: Two: one holds, the other installs Windows on it",
    "Windows is...a 64 bit rewrite of...a 32 bit extension to...a 16 bit api to...an 8 bit kernel for...a 4 bit microprocessor by...a 2 bit company that can't stand...1 bit of competition.",
    "The shortest programmer joke: 'I'm nearly done!'",
    "JIT Happens!",
    "I � Unicode.",
    "What do you call a programmer from Finland? Nerdic.",
    "Q: What did the Java code say to the C code? A: You've got no class.",
    "Why did Microsoft name their new search engine BING? Because It's Not Google!",
    "A classic one from learning finite state machines: 'Kleeneliness is next to Gödeliness'",
    "Pirates go arg! Computer pirates go argv!",
    "Software salesmen and used-car salesmen differ in that the latter know when they are lying.",
    "Child: Dad, why does the sun rise in the east and set in the west? Dad: Son, it's working, don't touch",
]

explicit = [
    "Programming is like sex: One mistake and you have to support it for the rest of your life.",
    "Software is like sex: It's better when it's free. (Linus Torvalds)",
    "Software is like sex: It's never REALLY free.",
    "There are 10 types of people in the world. Those who understand binary and those who get laid.",
    "Why programmers like UNIX: unzip, strip, touch, finger, grep, mount, fsck, more, yes, fsck, fsck, fsck, umount, sleep",
    "If your mom was a collection class, her insert method would be public.",
    "Your mommas so fat that not even Dijkstra is able to find a shortest path around her.",
    "C++ - where your friends have access to your private members.",
    "The only 'intuitive' user interface is the nipple. After that, it's all learned.",
    "During a recent password audit, it was found that a blonde was using the following password: MickeyMinniePlutoHueyLouieDeweyDonaldGoofy. When asked why such a big password, she said that it had to be at least 8 characters long.",
    "Q: What's the difference between Software Development and Sex? A: In sex, you don't get a bonus for releasing early.",
]

"""
Jokes from The Internet Chuck Norris DB (ICNDB) (http://www.icndb.com/) - provided under CC BY-SA 3.0
http://api.icndb.com/jokes/
"""

chuck = [
    "The Chuck Norris military unit was not used in the game Civilization 4, because a single Chuck Norris could defeat the entire combined nations of the world in one turn.",
    "Chuck Norris is the only human being to display the Heisenberg uncertainty principle - you can never know both exactly where and how quickly he will roundhouse-kick you in the face.",
    "Chuck Norris originally appeared in the 'Street Fighter II' video game, but was removed by Beta Testers because every button caused him to do a roundhouse kick. When asked about this glitch, Norris replied 'That's no glitch.'",
    "Scientists have estimated that the energy given off during the Big Bang is roughly equal to 1CNRhK (Chuck Norris Roundhouse Kick).",
    "When Chuck Norris throws exceptions, it's across the room.",
    "All arrays Chuck Norris declares are of infinite size, because Chuck Norris knows no bounds.",
    "Chuck Norris doesn't have disk latency because the hard drive knows to hurry the hell up.",
    "Chuck Norris writes code that optimizes itself.",
    "Chuck Norris can't test for equality because he has no equal.",
    "Chuck Norris doesn't need garbage collection because he doesn't call .Dispose(), he calls .DropKick().",
    "Chuck Norris's first program was kill -9.",
    "Chuck Norris burst the dot com bubble.",
    "All browsers support the hex definitions #chuck and #norris for the colors black and blue.",
    "MySpace actually isn't your space, it's Chuck's (he just lets you use it).",
    "Chuck Norris can write infinite recursion functions and have them return.",
    "Chuck Norris can solve the Towers of Hanoi in one move.",
    "The only pattern Chuck Norris knows is God Object.",
    "Chuck Norris finished World of Warcraft.",
    "Project managers never ask Chuck Norris for estimations... ever.",
    "Chuck Norris doesn't use web standards as the web will conform to him.",
    "'It works on my machine' always holds true for Chuck Norris.",
    "Chuck Norris doesn't do Burn Down charts, he does Smack Down charts.",
    "Chuck Norris can delete the Recycling Bin.",
    "Chuck Norris's beard can type 140 wpm.",
    "Chuck Norris can unit test entire applications with a single assert.",
    "Chuck Norris doesn't bug hunt as that signifies a probability of failure, he goes bug killing.",
    "Chuck Norris's keyboard doesn't have a Ctrl key because nothing controls Chuck Norris.",
    "When Chuck Norris is web surfing websites get the message 'Warning: Internet Explorer has deemed this user to be malicious or dangerous. Proceed?'.",
    "Chuck Norris can overflow your stack just by looking at it.",
    "To Chuck Norris, everything contains a vulnerability.",
    "Chuck Norris doesn't need sudo, he just types 'Chuck Norris' before his commands.",
    "Chuck Norris doesn't need a debugger, he just stares down the bug until the code confesses.",
    "Chuck Norris can access private methods.",
    "Chuck Norris can instantiate an abstract class.",
    "Chuck Norris does not need to know about class factory pattern. He can instantiate interfaces.",
    "The class object inherits from Chuck Norris",
    "For Chuck Norris, NP-Hard = O(1).",
    "Chuck Norris knows the last digit of PI.",
    "Chuck Norris' Internet connection is faster upstream than downstream because even data has more incentive to run from him than to him.",
    "Chuck Norris solved the Travelling Salesman problem in O(1) time. Here's the pseudo-code: Break salesman into N pieces. Kick each piece to a different city.",
    "No statement can catch the ChuckNorrisException.",
    "Chuck Norris doesn't pair program.",
    "Chuck Norris can write multi-threaded applications with a single thread.",
    "Chuck Norris doesn't need to use AJAX because pages are too afraid to postback anyways.",
    "Chuck Norris doesn't use reflection, reflection asks politely for his help.",
    "There is no Esc key on Chuck Norris' keyboard, because no one escapes Chuck Norris.",
    "Chuck Norris can binary search unsorted data.",
    "Chuck Norris breaks RSA 128-bit encrypted codes in milliseconds.",
    "Chuck Norris doesn't needs try-catch, exceptions are too afraid to raise.",
    "Chuck Norris went out of an infinite loop.",
    "If Chuck Norris writes code with bugs, the bugs fix themselves.",
    "Chuck Norris hosting is 101% uptime guaranteed.",
    "Chuck Norris's keyboard has the Any key.",
    "Chuck Norris can access the DB from the UI.",
    "Chuck Norris' programs never exit, they terminate.",
    "Chuck Norris insists on strongly-typed programming languages.",
    "Chuck Norris protocol design method has no status, requests or responses, only commands.",
    "Chuck Norris programs occupy 150% of CPU, even when they are not executing.",
    "Chuck Norris can spawn threads that complete before they are started.",
    "Chuck Norris programs do not accept input.",
    "Chuck Norris can install iTunes without installing Quicktime.",
    "Chuck Norris doesn't need an OS.",
    "Chuck Norris's OSI network model has only one layer - Physical.",
    "Chuck Norris can compile syntax errors.",
    "Every SQL statement that Chuck Norris codes has an implicit 'COMMIT' in its end.",
    "Chuck Norris does not need to type-cast. The Chuck-Norris Compiler (CNC) sees through things. All way down. Always.",
    "Chuck Norris does not code in cycles, he codes in strikes.",
    "Chuck Norris compresses his files by doing a flying round house kick to the hard drive.",
    "Chick Norris solved the halting problem.",
    "With Chuck Norris P = NP. There's no nondeterminism with Chuck Norris decisions.",
    "Chuck Norris can retrieve anything from /dev/null.",
    "No one has ever pair-programmed with Chuck Norris and lived to tell about it.",
    "No one has ever spoken during review of Chuck Norris' code and lived to tell about it.",
    "Chuck Norris doesn't use GUI, he prefers COMMAND line.",
    "Chuck Norris doesn't use Oracle, he is the Oracle.",
    "Chuck Norris can dereference NULL.",
    "A diff between your code and Chuck Norris's is infinite.",
    "The Chuck Norris Eclipse plugin made alien contact.",
    "Chuck Norris is the ultimate mutex, all threads fear him.",
    "Chuck Norris uses canvas in IE.",
    "Don't worry about tests, Chuck Norris's test cases cover your code too.",
    "Each hair in Chuck Norris's beard contributes to make the world's largest DDOS.",
    "Chuck Norris's log statements are always at the FATAL level.",
    "Chuck Norris's database has only one table, 'Kick', which he DROPs frequently.",
    "Chuck Norris finished World of Warcraft.",
    "When Chuck Norris break the build, you can't fix it, because there is not a single line of code left.",
    "Chuck Norris types with one finger. He points it at the keyboard and the keyboard does the rest.",
    "Chuck Norris's programs can pass the Turing Test by staring at the interrogator.",
    "If you try to kill -9 Chuck Norris's programs, it backfires.",
    "Chuck Norris does infinit loops in 4 seconds.",
    "Product Owners never ask Chuck Norris for more features. They ask for mercy.",
    "Product Owners never argue with Chuck Norris after he demonstrates the DropKick feature.",
    "Chuck Norris can over-write a locked variable.",
    "Chuck Norris knows the value of NULL, and he can sort by it too.",
    "Chuck Norris can install a 64 bit OS on 32 bit machines.",
    "Chuck Norris can write to an output stream.",
    "Chuck Norris can read from an input stream.",
    "Chuck Norris never has to build his program to machine code. Machines have learnt to interpret Chuck Norris code.",
    "Chuck Norris' unit tests don't run. They die.",
    "Chuck Norris causes the Windows Blue Screen of Death.",
    "Chuck Norris can download emails with his pick-up.",
    "Chuck Norris can make a class that is both abstract and final.",
    "Chuck Norris could use anything in java.util.* to kill you, including the javadocs.",
    "Code runs faster when Chuck Norris watches it."
]
