# -*- coding: utf-8 -*-

# BRAZILIAN PORTUGUESE

"""
Jokes below come from the "jokes_en.py" file.
Translation to Brazilian Portuguese: Vitor Mello - provided under CC BY-SA 3.0
"""

neutral = [
    "Usuários de Ubuntu provavelmente vão entender essa piada.",
    "Triunfantemente, Beth removeu o Python 2.7 de seu servidor em 2030.",
    "Uma query SQL entra em um bar, vai até duas tabelas e pergunta: 'posso me juntar a vocês?'",
    "Se você colocar um milhão de macacos em um milhão de teclados, um deles eventualmente escreverá um programa em Java. Os demais escreverão Perl.",
    "Para entender recursão, você precisa primeiro entender recursão.",
    "Eu sugeri realizar um seminário de Dinâmica de Reutilização Orientada a Gestão de Aplicações, mas a sigla foi impopular.",
    "'Toc toc.' 'Quem é?' … longa pausa … 'Java.'",
    "Quantos programadores são necessários para trocar uma lâmpada? Nenhum, isso é um problema de hardware.",
    "Qual é a forma orientada a objetos de ficar rico? Herança.",
    "Dois Threads entram em um bar, o atendente olha e diz,'Eii, sem condições de corrida como na última vez'.",
    "Programadores C antigos não morrem, eles apenas são convertidos para void.",
    "Oito bytes entram em um bar. O barman pergunta o que querem. 'Um double.'",
    "Desenvolvedores de software gostam de resolver problemas. Se não houver nenhum disponível, eles vão criar o próprio.",
    ".NET foi nomeado assim para não aparecer em uma listagem de diretório Unix.",
    "Otimista: o copo está meio cheio. Programador: o copo é duas vezes maior do que o necessário.",
    "Em C tínhamos que criar nossos próprios bugs. Em C++ podemos herdá-los.",
    "Como você chama um programador da Finlândia? Nerdic.",
    "O código Java disse ao código C: 'você não tem classe'.",
    "Piratas dizem “arg!”, piratas de computador dizem 'argv!'.",
    "Vendedores de software e vendedores de carros usados diferem… porque os últimos sabem quando estão mentindo.",
    "Filho: pai, por que o sol nasce no leste? Pai: está funcionando, não mexe.",
    "Por que programadores confundem Halloween com Natal? Porque OCT 31 == DEC 25.",
    "Quantos programadores Prolog são necessários para trocar uma lâmpada? false.",
    "Programadores de verdade conseguem escrever assembly em qualquer linguagem.",
    "Garçom: café ou chá? Programador: sim.",
    "Debugging é como ser o detetive em um drama policial onde você também é o assassino.",
    "Aprender JavaScript é como olhar pros dois lados antes de atravessar a rua e mesmo assim ser atingido por um avião.",
    "Quando seu código não muda de cor automaticamente, algo está errado… eu sinto isso.",
    "Tenho uma piada de programação, mas ela só funciona no meu computador.",
    "Bug? Isso não é bug, é feature.",
    "Não compute e dirija; a vida que você salvar pode ser a sua.",
    "Se no começo você não conseguir, chame de versão 1.0.",
    "Eu tenho um sonho: 1073741824 bytes livres.",
    "Eu não perdi a minha mente; ela está salva em fita em algum lugar.",
    "Ler no banheiro é considerado multitarefa?",
    "Nunca diga 'OPS!', diga 'ah, interessante!'.",
    "Pressione CTRL-ALT-DEL para continuar...",
    "A caixa dizia: 'instale no Windows 95, NT 4.0 ou superior'. Então eu instalei no Linux.",
    "O programa está absolutamente certo; portanto o computador deve estar errado.",
    "Existem apenas 10 tipos de pessoas no mundo: as que entendem binário e as que não entendem.",
    "Já havia computadores nos tempos bíblicos. Eva tinha um Apple.",
    "Erro de usuário: substitua o usuário e pressione qualquer tecla para continuar.",
    "Por que queremos terminais inteligentes quando existem tantos usuários estúpidos?",
    "Windows NÃO é um vírus. Vírus fazem alguma coisa.",
    "Você está progredindo se cada erro for um novo.",
    "Você tinha e-mail, mas o superusuário leu e deletou!",
    "Você nunca termina um programa, você apenas para de trabalhar nele.",
    "Você não precisa saber como o computador funciona, apenas como usar o computador.",
    "Você esqueceu de fazer backup há 16 dias. Amanhã você vai precisar dessa versão.",
    "Minha banda favorita baseada em computador é Black IPs.",
    "Por que o desenvolvedor faliu? Ele usou todo o cache.",
    "Inteligência artificial geralmente vence estupidez real.",
    "Bugs entram pelas janelas abertas (Windows).",
    "Unix é amigável com o usuário. Só é seletivo com quem ele faz amizade.",
    "Falha não é uma opção. Ela vem junto com seu produto Microsoft.",
    "Computadores são como ar-condicionado: param de funcionar quando você abre muitas janelas.",
    "Eu não sou antissocial; eu apenas não sou amigável ao usuário.",
    "Ei! Compilou! Pode lançar!",
    "Se Ruby não é e Perl é a resposta, você não entendeu a pergunta.",
    "Minha atitude não é ruim. Ela está em beta.",
    "Programadores são ferramentas para converter cafeína em código.",
    "Existem três tipos de pessoas: as que sabem contar e as que não sabem.",
    "Por que programadores preferem modo escuro? Porque luz atrai bugs.",
    "Por que programadores odeiam a natureza? Muitos bugs.",
    "Tenho uma piada de HTTP, mas se eu fizer POST você não vai GET.",
    "Programador não tem bug, tem feature surpresa.",
    "Senior com 99 problemas + Junior com 1 = Senior com 100 problemas.",
    "Erro 404: Motivação não encontrada.",
    "O melhor backup é aquele que nunca foi preciso usar.",
    "Todo código legado já foi código novo um dia.",
    "Por que o computador foi ao terapeuta? Porque tinha problemas de processamento emocional",
    "Programador só confia em duas coisas: café e 'funciona na minha máquina'",
    "Aluno: 'posso entregar amanhã?' Professor: 'pode'. Sistema: não.",
    "Deploy na sexta-feira é ritual de invocação de problemas.",
    "Aluno de programação aprende duas coisas: código e sofrimento existencial.",
    "O bug não foi encontrado, ele foi convidado a sair educadamente.",
    "O bug não é erro, é experiência de aprendizado avançado.",
    "Um programador entrou no ônibus e disse que ia debugar o trajeto. O ônibus quebrou no meio do caminho."
]

chuck = [
    "Chuck Norris não depura código. O código se corrige sozinho.",
    "Quando Chuck Norris lança exceções, elas vão parar do outro lado da sala.",
    "Todos os arrays que Chuck Norris declara têm tamanho infinito, porque Chuck Norris não conhece limites.",
    "Chuck Norris não tem latência de disco porque o disco rígido sabe que precisa se apressar, ou então...",
    "Chuck Norris escreve código que se otimiza sozinho.",
    "Chuck Norris não pode testar igualdade porque ele não tem igual.",
    "Chuck Norris não precisa de garbage collector porque ele não chama .Dispose(), ele chama .DropKick().",
    "O primeiro programa de Chuck Norris foi kill -9.",
    "Todos os navegadores suportam as definições hex #chuck e #norris para as cores preto e azul.",
    "MySpace não é realmente seu espaço, é do Chuck (ele só deixa você usar).",
    "Chuck Norris pode escrever funções recursivas infinitas e ainda fazê-las retornar.",
    "Chuck Norris resolve as Torres de Hanói em um único movimento.",
    "Chuck Norris zerou World of Warcraft.",
    "Gerentes de projeto nunca pedem estimativas para Chuck Norris.",
    "Chuck Norris não usa padrões web; a web se adapta a ele.",
    "'Funciona na minha máquina' sempre é verdade para Chuck Norris.",
    "Chuck Norris pode deletar a Lixeira.",
    "A barba de Chuck Norris digita 140 palavras por minuto.",
    "Chuck Norris consegue testar aplicações inteiras com uma única asserção: “funciona”.",
    "Chuck Norris não caça bugs, porque isso sugere chance de falha; ele vai direto para o extermínio de bugs.",
    "O teclado de Chuck Norris não tem tecla Ctrl porque nada controla Chuck Norris.",
    "Chuck Norris consegue estourar sua stack só de olhar para ela.",
    "Para Chuck Norris, tudo contém uma vulnerabilidade.",
    "Chuck Norris não usa sudo; o shell simplesmente sabe que é ele e obedece.",
    "Chuck Norris não precisa de debugger; ele encara o código até ele confessar.",
    "Chuck Norris pode acessar métodos privados.",
    "Chuck Norris pode instanciar uma classe abstrata.",
    "O objeto Class herda de Chuck Norris.",
    "Para Chuck Norris, NP-difícil = O(1).",
    "Chuck Norris conhece o último dígito de Pi.",
    "A conexão de internet de Chuck Norris é mais rápida no upload do que no download, porque até os dados preferem fugir dele do que ir até ele.",
    "Chuck Norris resolveu o problema do caixeiro-viajante em O(1): ele divide o caixeiro em N partes e manda cada uma para uma cidade diferente.",
    "Nenhuma instrução consegue capturar a ChuckNorrisException.",
    "Chuck Norris não faz programação em par.",
    "Chuck Norris consegue escrever aplicações multithread usando apenas uma thread.",
    "Chuck Norris não precisa de AJAX porque as páginas têm medo de fazer postback.",
    "Não existe tecla Esc no teclado de Chuck Norris, porque ninguém escapa dele.",
    "Chuck Norris pode fazer busca binária em dados não ordenados.",
    "Chuck Norris não precisa de try-catch; exceções têm medo de acontecer.",
    "Chuck Norris saiu de um loop infinito.",
    "Se Chuck Norris escreve código com bugs, os bugs se consertam sozinhos.",
    "O teclado de Chuck Norris tem a tecla 'Qualquer'.",
    "Chuck Norris pode acessar o banco de dados pela interface de usuário.",
    "Programas de Chuck Norris nunca saem; eles são exterminados.",
    "Chuck Norris insiste em linguagens fortemente tipadas.",
    "O método de design de protocolo do Chuck Norris não tem status, requisições ou respostas, apenas comandos.",
    "Os programas de Chuck Norris ocupam 150% da CPU, mesmo quando não estão rodando.",
    "Chuck Norris pode criar threads que terminam antes de serem iniciadas.",
    "Os programas de Chuck Norris não aceitam entrada.",
    "Chuck Norris pode instalar iTunes sem instalar QuickTime.",
    "Chuck Norris não precisa de sistema operacional.",
    "O modelo OSI de Chuck Norris tem apenas uma camada: física.",
    "Chuck Norris pode compilar erros de sintaxe.",
    "Toda instrução SQL que Chuck Norris escreve tem um “COMMIT” implícito no final.",
    "Chuck Norris não precisa de type-cast. O compilador Chuck Norris (CNC) vê através de tudo. Sempre.",
    "Chuck Norris não programa em ciclos, ele programa em golpes.",
    "Chuck Norris comprime arquivos dando um chute giratório no disco rígido.",
    "Chuck Norris comprime arquivos dando um chute giratório no disco rígido.",
    "Chuck Norris pode recuperar qualquer coisa de /dev/null.",
    "Ninguém nunca fez programação em par com Chuck Norris e sobreviveu para contar.",
    "Um vírus contaminou Chuck Norris, e após três dias sofrendo, ele foi eliminado",
    "Ninguém nunca falou durante a revisão de código de Chuck Norris e sobreviveu para contar.",
    "Chuck Norris não usa GUI, ele prefere linha de comando.",
    "Chuck Norris não usa Oracle, ele é o Oracle.",
    "A diferença entre seu código e o de Chuck Norris é infinita.",
    "O plugin do Eclipse do Chuck Norris fez contato com alienígenas.",
    "Uma vez Chuck Norris se impressionou... E isso ficou conhecido como sinal 'WOW'.",
    "Chuck Norris é o mutex definitivo, todas as threads o temem.",
    "Não se preocupe com testes, os casos de teste de Chuck Norris cobrem seu código também.",
    "Cada fio da barba de Chuck Norris contribui para o maior ataque DDoS do mundo.",
    "As mensagens de log de Chuck Norris estão sempre no nível FATAL.",
    "O banco de dados de Chuck Norris tem apenas uma tabela, “Kick”, que ele derruba frequentemente.",
    "Quando Chuck Norris quebra o build, você não pode consertar, porque não sobra nenhuma linha de código.",
    "Chuck Norris digita com um dedo. Ele aponta para o teclado e o teclado faz o resto.",
    "Os programas de Chuck Norris passam no teste de Turing só de encarar o interrogador.",
    "Se você tentar usar kill -9 nos programas de Chuck Norris, isso volta contra você.",
    "Chuck Norris executa loops infinitos em menos de 4 segundos.",
    "Chuck Norris pode sobrescrever uma variável bloqueada.",
    "Chuck Norris conhece o valor de NULL e também pode ordenar por ele.",
    "Chuck Norris pode instalar um sistema operacional 64-bit em máquinas 32-bit.",
    "Chuck Norris nunca precisa compilar seu código para máquina. As máquinas aprenderam a interpretar o código dele.",
    "Os testes unitários de Chuck Norris não rodam. Eles morrem.",
    "Chuck Norris causa a Tela Azul da Morte."

]

jokes_pt_br = {
    "neutral": neutral,
    "chuck": chuck,
    "all": neutral + chuck,
}