# -*- coding: utf-8 -*-

neutral = [
    "Was steht auf dem Grabstein eines Mathematikers? 'Damit hat er nicht gerechnet.'",
    "Mercedes Benz ist es nun gelungen, für eine Entwicklungssumme von über einer Milliarde Euro ein Auto zu entwickeln, welches sich bei Gefahr auf den Rücken legt und tot stellt.",
    "Wenn ein Yogalehrer seine Beine senkrecht nach oben streckt und dabei furzt, welche Yoga Figur stellt er da? Eine Duftkerze.",
    "Frage: Was ist das beste geschenkt für trump? Antwort : klopapier was soll man einem arschloch denn sonst schenken",
    "Warum freut sich eine Blondine so, wenn sie ein Puzzle nach 6 Monaten fertig hat? – Weil auf der Packung steht: 2-4 Jahre.",
    "Sitzen 2 Polen im Auto, kommt die Polizei: 'Wir suchen 2 Autodiebe.' Schauen sich die Polen an: 'Wir machen’s.'",
    "Ich wollte Spiderman anrufen, aber er hatte kein Netz.",
    "Sitzen 2 Bomben im Keller. Sagt die eine: 'Komm, lass hoch gehen.'",
    "Wie nennt man einen übergewichtigen Vegetarier? Biotonne",
    "Wie nennt man jemand der so tut als würde er etwas werfen? – Einen Scheinwerfer.",
    "Was steht auf dem Grabstein einer Putzfrau? – 'Sie wird nie wieder kehren.'",
    "Abwasser ist ein Thema, das unbedingt geklärt werden muss.",
    "Warum ging der Luftballon kaputt? – Aus Platzgründen.",
    "Was steht auf dem Grabstein eines Spanners? – „Der ist weg vom Fenster.“",
    "Warum können Geister so schlecht lügen? – Weil sie so leicht zu durchschauen sind.",
    "Bei Adidas wurde eingebrochen. Was macht die Polizei? Sie schickt 3 Streifen.",
    "Was machen zwei Polen auf dem Eis? Einbrechen.",
    "Egal wie dicht du bist, Goethe war Dichter.",
    "Wie war die Stimmung in der DDR ? - Sie hielt sich in Grenzen",
    "Auch im Osten trägt man Westen.",
    "Was bekommt ein Kannibale wenn er zu spät zum Essen kommt? Die kalte Schulter.",
    "Was steht auf dem Grabstein eines Geisterfahrers? – „Entgegenkommend – bis zuletzt.“",
    "Was ist ein Keks unter einem Baum? – Ein schattiges Plätzchen.",
    "Warum geht der Sarg nicht auf? – Weil ein Zuhälter drin liegt.",
    "Treffen sich zwei Blitze. -Hey, schlag’ ein !",
    "Was macht ein Terrorist im Treppenhaus? - Hoch gehen",
    "Das Motto eines McDonald’s-Angestellten? Frittieren geht über Studieren.",
    "Ein Polizist hält Kai an, der im Dunkeln mit dem Fahrrad unterwegs ist. „Deine Lampe ist kaputt. Du musst absteigen und schieben!“ Darauf sagt Kai: „Hab ich schon versucht, aber da geht die Lampe auch nicht!“",
    "Sitzen zwei Frosche auf einem Stein. Es fängt an zu regnen. Sagt der eine Frosch zum andern:  „Lass uns ins Wasser springen, dann werden wir nicht nass.“",
    "In der Kirche liegen ein paar Schlittschuhe. „Wem gehören die denn?“, fragt der Pfarrer den jüngsten Messdiener. „Na wahrscheinlich den Eisheiligen!“",
    "Schimpft der Vater: „Mein Sohn, ich sage dir, wenn man will, kann man alles!“ – „Ach, wirklich? Dann versuch mal, eine Drehtür zuzuschlagen!“",
    "Zwei Bären sitzen vor ihrer Höhle und schauen zu, wie im Herbst das Laub von den Bäumen fällt. Da sagt einer der Bären: „Eins sag’ ich dir, irgendwann lasse ich den Winterschlaf ausfallen und sehe mir den Typen an, der im Frühling die Blätter wieder an die Bäume klebt!“",
    "Alle Tiere warten in einer langen Schlange vor Noahs Arche. Plötzlich stockt der lange Zug. Da sagt der Frosch zur Giraffe: „Guck mal, was da los ist!“ Die Giraffe reckt ihren langen Hals und sagt dann seufzend: „Das kann lange dauern. Der Tausendfüßler zieht sich gerade seine Hausschuhe an!",
    "Sagt der Bauer zu seinem Urlaubsgast: „Bei uns auf dem Land, weckt einen der Hahn.“ – „Sehr gut, bitte auf 11 Uhr stellen!“",
    "Fragt der Richter den Angeklagten: „Wo waren Sie zwischen 3 und 4?“ – „Im Kindergarten!“, antwortet der Angeklagte.",
    "Kai: „Du, Max, ich war schon immer ein ganz schön kluges Kind. Ich konnte schon vor meinem ersten Geburtstag laufen. Max: „Das nennst du klug? Ich habe mich bis zu meinem sechsten Lebensjahr tragen lassen.”",
    "Zwei Hühner stehen vor dem Schaufenster eines Kaufhauses und bewundern die dort ausgestellten Eierbecher. Sagt das eine Huhn: „Was für schöne Kinderwagen die haben!“",
    "Der Lehrer  fragt : „Warum ist Strom so wichtig?“ Peter antwortet: „Wenn es keinen Strom gäbe, müssten wir bei Kerzenlicht fernsehen.“",
    "Maxi kommt von der Schule nach Hause und erzählt: „Der Lehrer hat heute gesagt, dass der Strom wieder teurer wird. Da kannst du aber froh sein, dass ich keine große Leuchte bin!“",
    "Franz bringt aus dem Urlaub einen Papagei mit und soll ihn verzollen. Der Zöllner liest laut aus den Bestimmungen vor: „Papagei ausgestopft: zollfrei. Papagei lebendig: 300 Euro.“ Da krächzt der Vogel aus dem Käfig: „Leute, macht bloß keinen Scheiß!“",
    "Die Mutter zu ihrem Sohn: „Kannst du bitte schnell den Salzstreuer auffüllen?“ Eine Stunde später kommt der Kleine schluchzend und schniefend aus der Küche: „Ich schaff’s einfach nicht, das Zeug durch die Löcher zu stopfen!“",
    "Ein Bauer wird gefragt, wie viele Schafe er hat. „Keine Ahnung. Immer wenn ich anfange zu zählen, schlafe ich ein.“",
    "Ein Mann kommt mit einem uralten Auto an die Tankstelle und sagt: „Ich hätte gern zwei Scheibenwischer für mein Auto.“ Sagt der Tankwart: „In Ordnung, das halte ich für einen fairen Tausch!“",
    "Die Nachbarn haben sich eine neue Mikrowelle gekauft. Niklas kommt ganz aufgeregt von nebenan nach Hause und ruft: „Mami, stell dir vor: Tante Huber kocht ihr Essen jetzt im Fernseher!“",
    "Herr Grünspan fragt die Kellnerin: „Was können Sie mir empfehlen? Ich habe Hunger wie ein Wolf!“– „Dann empfehle ich Ihnen unseren Lammbraten!“",
    "Was ist schlimmer als ein Wurm im Apfel? – Ein halber Wurm in einem angebissenen Apfel.",
    "Ein Gauner jammert vor Gericht: 'Herr Richter, Ihnen kann man auch nichts recht machen. Breche ich ein, werde ich verurteilt, breche ich aus, werde ich auch verurteilt!'",
    "Der Ehemann kommt in die Küche und sagt zu seiner Frau: 'Aber Liebling, du brauchst an deinem Geburtstag doch nicht zu spülen! Mach es morgen!'",
    "Emma kommt mit nassen Haaren ins Wohnzimmer. Schimpft der Vater:„Musst du eigentlich jeden Abend deinem Goldfisch einen Gute-Nacht-Kuss geben?“",
    "Lukas beschwert sich zu Hause: „Diese doofe Lehrerin! Beklagt sich über meine Schrift, dabei sehen ihre Einser wie Vierer aus!“",
    "Der Fußballtrainer brüllt die Mannschaft an: 'Ich habe euch gesagt: Spielt, wie ihr noch nie gespielt habt - und nicht: Spielt, als wenn ihr noch nie gespielt hättet!'",
    "Clara fragt ihre Mutter: „Weißt du, wie viel Zahnpasta in einer Tube steckt?“ – „Nein, du etwa?“ – „Ja, ich hab es gerade ausprobiert: Etwas mehr als vier Meter!“",
    "Ein Elektriker soll bei Familie Maier einen Schaden beheben. Als er klingelt, bekommt er einen derart heftigen Stromschlag, dass es ihn der Länge nach auf den Boden befördert. Als Frau Maier die Tür öffnet, meint sie zufrieden: „Ah ja. Wie ich sehe, haben Sie den Schaden bereits gefunden.“",
    "Eine alte Dame trinkt zum ersten Mal einen Whisky. Sie überlegt eine Weile und meint dann: „Merkwürdig, das Zeug schmeckt genau so wie die Medizin, die mein seliger Mann zwanzig Jahre lang einnehmen musste…“",
    "Treffen sich zwei ältere Herren. Sagt der eine: „Sag mal, hast Du eigentlich deine Hochzeitsschuhe noch?“ Antwortet der andere: „Nein, aber die alte Schachtel hab ich noch zu Hause…“",
    "„Ich muss Ihnen einen furchtbare Mitteilung überbringen“, sagt die Wahrsagerin zur Ehefrau. „Ihr Mann wird morgen sterben!“ Antwortet die Frau: „Ich weiß. Ich möchte nur wissen, ob ich freigesprochen werde…“",
    "Sie: „Ich hatte Dir doch gesagt, 2 Bier und um 22 Uhr bist Du wieder zu Hause!“ Er: „Ach, so herum war das…“",
    "Ein Mann stochert mürrisch in seinem Essen herum. „Ist das wieder aus der Dose?“ – „Ja, Schatz, es war so ein süßer Hund abgebildet und darunter stand ‚Für ihren Liebling’…“",
    "Die Kundin: „Ich brauche Äpfel für meinen Mann, sind diese hier mit einem Gift bespritzt?“ – „Nein, das müssen Sie schon selber machen!“",
    "Kommt ein Hahn mit einem Straußenei auf seine Hühnerfarm: „Mädels, ich will ja nicht meckern, aber schaut mal, was die Konkurrenz macht…“",
    "Als der reiche Amerikaner den von ihm bestellten Trabi bekommt, sagt er voller Anerkennung: „Diese Deutschen – immer gründlich! Bevor sie das Auto liefern, schicken sie einem erst mal ein Plastikmodell…“",
    "„Hat das Medikament, das sie mir da verschreiben, auch irgendwelche Nebenwirkungen?“ – „Ja, Sie müssen damit rechnen, wieder arbeitsfähig zu werden!“",
    "„Guten Tag, mein Herr“, sagt der Optiker zum eintretenden Kunden, „Sie brauchen eine neue Brille mit minus 9 Dioptrien.“ Der Kunde verblüfft: „Wie können Sie denn das auf Anhieb so präzise beurteilen?“ Darauf der Optiker: „Weil Sie durchs Schaufenster statt durch die Tür gekommen sind!“",
]
adult = [
    "Ein Pärchen beim Sex. Sie fängt an zu stöhnen: 'Jaa, gib's mir.' Sag mir dreckige Sachen!  'Er:' Küche, Bad, Wohnzimmer ",
    "Warum ist Sex mit der Lehrerin besser als mit der Krankenschwester? Die Krankenschwester sagt: 'Der nächste bitte!' und die Lehrerin sagt: 'Wir wiederholen das ganze!'",
    "Frau beim Sex: 'Was jetzt, raus oder rein!'",
    "Eine Frau geht zum Arzt und sagt: 'Herr Doktor,' immer wenn ich rauche denke ich an Sex, was soll ich tun? 'Doktor:'Ach, erst rauchen wir mal eine und dann sehen wir weiter!",
    "Nach dem Sex im Bett: 'Frau:' 'Woran denkst du?''Mann:''Kennst du nicht!'",
    "Treffen sich zwei Freunde.'Stell dir vor,' ich habe heute Morgen meine Frau mit Oralverkehr geweckt.'Und, was hat sie gesagt?''Laff daff!'",
    "Paul stößt in der Hotelhalle versehentlich mit dem Ellenbogen an den Busen einer jungen Frau. 'Er entschuldigt sich mit den Worten:' 'Wenn Ihr Herz so zart ist wie Ihr Busen werden Sie mir sicherlich verzeihen.''Da lächelt sie zurück uns sagt:' 'Und wenn Ihr Ding so hart ist wie Ihr Ellenbogen, dann besuchen Sie mich doch mal auf Zimmer 23!'",
    "Der Weihnachtsmann, als er das nackte Mädchen auf dem Sofa findet: 'Tu ichs, komme ich nicht wieder in den Himmel. Tu ichs nicht, komme ich nicht wieder durch den Kamin.'",
    "Ein Ehepaar ruft die Rettung an: 'Kommen Sie schnell! Unser Kind hat ein Kondom geschluckt!' Ein paar Minuten später kommt ein zweiter Anruf: 'Sie brauchen nicht mehr kommen. Wir haben ein anderes gefunden.'",
    " Kommt ein Opa in den Puff und erkundigt sich nach den Preisen. Die Puffmutter: '100 im Bett, 50 im Stehen, 10 auf dem Teppich!' Opa legt einen Hunderter auf den Tresen. Die Puffmutter: 'Gell, im Bett ist es immer noch am schönsten!' Opa: 'Was heisst hier Bett? Zehnmal Teppich!'", 
    "Was haben ein Schäferhund und ein kurzsichtiger Gynäkologe gemeinsam? Eine feuchte Nase",
    "'Ich habe schrecklich Zahnschmerzen.' - 'Das kenne ich, letzte Woche hatte ich auch welche. Da habe ich mit meiner Frau geschlafen und schon waren sie weg.' - 'Toll, meinst Du, Deine Frau hätte heute Zeit für mich?'",
    "Fritzchen entdeckt beim Spaziergang etwas unter dem Bauch eines Hengstes, das er noch nie gesehen hat. Er fragt seine Mutter: „Du Mama, ist das Pferd krank?“ Die Mutter schaut und sagt: „Nein, aber ich wünschte, dein Vater wäre so gesund…“ ",
    "Ein Ehepaar hat zwei hübsche Töchter und einen hässlichen Jungen. Fragt der Ehemann beim Blick auf den Jungen: „Sag mal, Du hast mich doch nicht etwa betrogen?“ Antwortet die Frau: „Nein, dieses Mal leider nicht…“",
    "Treffen sich zwei Bauern. Sagt der eine Bauer zum anderen: „He, Sepp, da hinten auf deinem Acker vögelt deine Frau mit deinem Knecht!“ Dreht sich der Sepp um und meint: „Das ist nicht mein Acker.“",

]
chuck = [
    "Chuck Norris streichelt keine Tiere, die Tiere streicheln sich selbst, wenn er in der Nähe ist",
    "Chuck Norris braucht die Toilette nicht zu spülen. Er sagt einfach  Buh!  und schon haut die Scheiße von alleine ab.",
    "Chuck Norris verwählt sich nicht. Wenn du abhebst, warst du am falschen Telefon.",
    "Chuck Norris hat einen Grizzlybär-Teppich. Der Bär lebt, hat bloß Angst, sich zu bewegen.",
    "Wenn Chuck Norris mit nassen Fingern an der Steckdose rumfummelt, kriegt das Kraftwerk einen Schlag.",
    "Chuck Norris kann mit Durchfall furzen.",
    "Chuck Norris klaut den Polen die Autos.",
    "Wenn Chuck Norris einen Raum betritt, stehen sogar die Stühle auf!",
    "Chuck Norris hat bei Burgerking einen Big Mac bestellt - und hat ihn ohne Wiederworte bekommen",
    "Chuck Norris war bereits auf dem Mars. Das ist der Grund dafür, warum es dort kein Leben mehr gibt.",
    "Chuck Norris wurde letztens von der Polizei angehalten... Die Polizisten sind mit einer Verwarnung davon gekommen.",
    "Chuck Norris kackt Lichtschwerter.",
    "Herr Norris benutzt keine Kondome, denn es gibt nichts, was vor ihm schützen könnte.",
    "Wie trinkt Chuck Norris seinen Kaffee? Antwort: Schwarz ohne Wasser!",
    "Was geht den Opfern von Chuck Norris als Letztes durch den Kopf: SEIN FUSS.",
    "Egal was dir Chuck Norris kocht. Es schmeckt einfach gut!",
    "Chuck Norris' Hund sammelt seine Haufen selbst ein, weil sich Chuck für niemanden bückt.",
    "Endlich weiß man, warum sich das Universum ausdehnt. Alles versucht sich so weit wie möglich von Chuck Norris zu entfernen.",
    "Chuck Norris' Computertastatur hat keine Löschtaste. Chuck Norris macht keine Fehler.",
    "Chuck Norris bekommt auch Geld für Flaschen ohne Pfand.",
    "Chuck Norris darf vom Beckenrand springen.",
    " Bill Gates lebt in ständiger Angst, dass der PC von Chuck Norris abstürzt.",
    "Der wahre Grund, warum sich Hitler tötete, ist dass Hitler herausgefunden hat, dass Chuck Norris Jude ist.",
    "Chuck Norris hat versucht Gewicht zu verlieren. Jedoch verliert Chuck niemals.",
    "Chuck Norris kann Drehtüren eintreten.",
    "Alle Menschen malen den Teufel an die Wand, der Teufel aber malt Chuck Norris an die Wand.",
    "Chuck isst keinen Honig, er kaut Bienen!",
    "Das Universum dehnt sich aus weil Chuck Norris furzt.",
    "Chuck war Kamikaze-Pilot… 12 mal.",
    "Einmal hat Herr Norris eine ganze Torte gegessen, bevor ihm jemand sagen konnte, dass eine Stripperin drin war.",
    " Chuck Norris darf die Straße neben dem Zebrastreifen überqueren.",
    "Was ist der Unterschied zwischen Chuck Norris und Gott? Gott kennt Gnade...",
    "Chuck Norris wurde von der hochgiftigen ... Black Mamba .. gebissen. Nach 3 Tagen Höllenqualen ist die Black Mamba verstorben.",
    "Chuck Norris hat keine Herzattacken. Kein Herz wäre so verrückt Chuck zu attackieren."
    "Chuck Norris kann einen Hut aus einem Hasen zaubern.",
    "Besser mit Chuck Norris teilen als von Chuck Norris geteilt zu werden. ",
    "Chuck Norris spielte GTA 5. Er tötet 45 Menschen, klaut 21 Autos und tut es mit 7 Prostituierten ......während das Spiel lädt!.",
    " Chuck Norris war in der Hölle. Der Teufel ist vor Angst gestorben."
    "Warum weinen Kinder wenn sie auf die Welt kommen, weil sie wissen dass sie eine Welt mit Chuck Norris betreten haben.",
    "Chuck Norris ist der Einzige, der die Zeit wirklich totschlagen kann.",
    "Wenn es wie Hühnchen riecht, wenn es wie Hühnchen aussieht und wenn es wie Hühnchen schmeckt, aber Chuck Norris sagt, es ist Rind, dann ist es Rind."
    "Chuck Norris ist Fallschirmspringen gegangen. Sein Fallschirm hat sich nicht geöffnet. Er ist den Fallschirm danach umtauschen gegangen. ",
    "Chuck Norris bekommt nie Spam-Emails.",
    "Chuck Norris wartet nicht auf die Bahn. Die Bahn wartet auf Chuck Norris. ",
    "Chuck Norris ist so hart, wenn er den Schleudersitz betätigt, wird nicht er sondern das Flugzeug weggeschleudert.",
    "Chuck Norris darf die Rettungsgasse auf der Autobahn benutzen. ",
    "Wie heißt das Tagebuch von Chuck Norris?...... Guinessbuch der Rekorde!",
    "Chuck Norris versteht Frauen.",
    "Chuck Norris brachte seinem Vater rasieren bei.",
    "Wenn Chuck Norris ins Kino geht, bekommt er ein Fernbedienung.",
    "Wenn Chuck Norris Fallschirmspringen geht, braucht er keinen Fallschirm. Der Fallschirm braucht ihn.",
    "Chuck Norris tank nicht. Das Auto fährt aus Respekt.",
    "In einem Zimmer gibt es 156 Dinge mit denen dich Chuck Norris töten kann, einschließlich dem Raum.",
    "Es gibt Aliens, welche die Welt erobern wollen. Sie warten nur bis Chuck Norris gestorben ist damit sie angreifen können!",
    "Chuck Norris furzt nur, um zu töten.",
    "Wenn Chuck Norris raucht, bekommt er keinen Lungenkrebs sondern die Zigarette Norriskrebs.",
    "Chuck braucht ein Stunt-Double. Aber nur in Szenen, in denen er weinen soll.",
    "Chuck Norris Tränen können theoretisch Krebs heilen, doch Chuck Norris weint nicht.",
    "Chuck Norris Haus hat keine Türen, sondern nur eine Mauer durch die er läuft.",
    "Chuck Norris hat einen Handgranate geschmissen und 50 Leute getötet. Danach explodierte die Granate.",
    "Chuck Norris kann dich mit einem Schnurlostelefon erwürgen.",
    "Chuck Norris bucht in einem Schweizer Hotel ein Zimmer mit Meerblick und bekommt es.",
    "Chuck Norris darf an Tankstellen rauchen.",
    "Chuck Norris spielt Paint-Ball ohne Maske. ",
    "Chuck Norris kennt keine Angst. Die Angst kennt ihn.",
    "Chuck Norris ist eigentlich vor 10 Jahren gestorben, der Tod hatte aber nie den Mut, es ihm zu sagen.",
    "Chuck Norris kann im Kinderkarussell überholen.",
    "Wenn sich ein Zug umbringen möchte, wirft er sich vor Chuck Norris. ",
    "Chuck Norris telefoniert trotz Tastensperre.",
    " Chuck Norris hat keinen Schatten. Die Wand möchte nur so aussehen wie Chuck Norris.",
   "Chuck Norris hat als Kind Sandburgen gebaut - heute nennt man sie Pyramiden.",
    "Chuck Norris kann eine Bank ausrauben und zwar per Telefonbanking.",
]

jokes_de = {
    'neutral': neutral,
    'all': neutral + adult + chuck,
    'adult': adult,
    'chuck': chuck,
}
