# -*- coding: utf-8 -*-

"""
Jokes from stackoverflow - provided under CC BY-SA 3.0
http://stackoverflow.com/questions/234075/what-is-your-best-programmer-joke?page=4&tab=votes#tab-top
"""

jokes = [
    "A SQL query goes into a bar, walks up to two tables and asks, \"Can I join you?\"",
    "When your hammer is C++, everything begins to look like a thumb.",
    "If you put a million monkeys at a million keyboards, one of them will eventually write a Java program. The rest of them will write Perl programs.",
    "To understand what recursion is, you must first understand recursion.",
    "Friends don't let friends use Python 2.7",
    "I suggested holding a 'Python Object Oriented Programming Seminar', but the acronym was unpopular.",
    "'Knock, knock.' 'Who’s there?' very long pause.....'Java.'",
    "How many programmers does it take to change a light bulb? None, that's a hardware problem.",
    "If you're happy and you know it, syntax error!",
    "'Whats the object-oriented way to become wealthy?' 'Inheritance'",
    "Programming is like sex: One mistake and you have to support it for the rest of your life.",
    "Software is like sex: It's better when it's free. (Linus Torvalds)",
    "Software is like sex: It's never REALLY free.",
    "Q: How many prolog programmers does it take to change a lightbulb? A: Yes.",
    "So this programmer goes out on a date with a hot chick.",
    "There are 10 types of people in the world. Those who understand binary and those who get laid.",
    "Why programmers like UNIX: unzip, strip, touch, finger, grep, mount, fsck, more, yes, fsck, fsck, fsck, umount, sleep",
    "Richard Stallman, Linus Torvalds, and Donald Knuth engage in a discussion on whose impact on computer science was the greatest. Stallman: 'God told me I have programmed the best editor in the world!' Torvalds: ''Well, God told me that I have programmed the best operating system in the world!' Knuth: 'Wait, wait, I never said that.'",
    "A foo walks into a bar, takes a look around and says 'Hello World!' and meet up his friends Alice, Bob, and Carol.",
    "Q: Why don't jokes work in octal? A: Because 7 10 11.",
    "If your mom was a collection class, her insert method would be public.",
    "A programmer started to cuss  Because getting to sleep was a fuss  As she lay there in bed  Looping 'round in her head was: while(!asleep()) sheep++",
    "Keyboard not found ... press F1 to continue",
    "Q: how many Microsoft programmers does it take to change a light bulb? A: none, they just make darkness a standard and tell everyone 'It's not a bug, it's a feature!'",
    "How long does it take to copy a file in Vista? Yeah, I don't know either, I'm still waiting to find out.",
    "Two bytes meet. The first byte asks, 'Are you ill?' The second byte replies, 'No, just feeling a bit off.'",
    "Two threads walk into a bar. The barkeeper looks up and yells, 'hey, I want don't any conditions race like time last!'",
    "Old C programmers don't die, they're just cast into void.",
    "Eight bytes walk into a bar. The bartender asks, 'Can I get you anything?' 'Yeah,' reply the bytes. 'Make us a double.'",
    "Your mommas so fat that not even Dijkstra is able to find a shortest path around her.",
    "C++ - where your friends have access to your private members.",
    "The only 'intuitive' user interface is the nipple. After that, it's all learned.",
    "Q: Why did the programmer quit his job? A: Because he didn't get arrays.",
    "XML is like violence. If it doesn't solve your problem, you're not using enough of it",
    "Why do java programmers have to wear glasses? Because they don't see sharp.",
    "Software developers like to solve problems. If there are no problems handily available, they will create their own problems.",
    "I'd like to make the world a better place, but they won't give me the source code.",
    "During a recent password audit, it was found that a blonde was using the following password: MickeyMinniePlutoHueyLouieDeweyDonaldGoofy .When asked why such a big password, she said that it had to be at least 8 characters long.",
    ".NET is called .NET so that it wouldn't show up in a Unix directory listing.",
    "What do you mean, it needs comments!? If it was hard to write, it should be hard to understand--why do you think we call it code???",
    "Hardware: The part of a computer that you can kick.",
    "Q: What's the difference between Software Development and Sex? A: In sex, you don't get a bonus for releasing early.",
    "The programmer got stuck in the shower because the instructions on the shampoo bottle said, Lather, Rinse, Repeat.",
    "Optimist : The glass is half full. Pessimist : The glass is half empty. Coder: The glass is twice as large as necessary.",
    "In C we had to code our own bugs. In C++ we can inherit them.",
    "Q: How come there is not obfuscated Perl contest? A: Because everyone would win.",
    "It's been said that if you play a Windows CD backwards, you'll hear satanic chanting...worse still if you play it forwards, it installs Windows.",
    "Q: How many programmers does it take to kill a cockroach? A: Two: one holds, the other installs Windows on it",
    "Windows is...a 64 bit rewrite of...a 32 bit extension to...a 16 bit api to...an 8 bit kernel for...a 4 bit microprocessor by...a 2 bit company that can't stand...1 bit of competition.",
    "The shortest programmer joke: 'I'm nearly done!'",
    "JIT Happens!",
    "I � Unicode.",
    "What do you call a programmer from Finland? Nerdic.",
    "Q: What did the Java code say to the C code? A: You've got no class.",
    "Why did Microsoft name their new search engine BING? Because It's Not Google!",
    "A classic one from learning finite state machines: 'Kleeneliness is next to Gödeliness'",
    "Pirates go arg! Computer pirates go argv!",
    "Software salesmen and used-car salesmen differ in that the latter know when they are lying.",
    "Child: Dad, why does the sun rise in the east and set in the west? Dad: Son, it's working, don't touch",
]
